apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: argocd
spec:
  project: microservice-project
  source:
    repoURL: 'https://github.com/kennethchinedu/microservice-DevOps'
    path: release
    targetRevision: main 
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry: 
      limit: 5
      backoff:
        duration: '5s'
        factor: 2
        maxDuration: '3m'