# We will deactivate default argocd project and create a different project to improve security

#Disabling  default project

# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: default
# spec:
#   sourceRepos: []
#   sourceNamespaces: []
#   destinations: []
#   namespaceResourceBlacklist:
#   - group: '*'
#     kind: '*' 



#Enabling new project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservice-project
  namespace: argocd
spec:
  description: Microservice Project
  sourceRepos:
    - 'https://github.com/kennethchinedu/microservice-DevOps' 
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*' 
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'NetworkPolicy' # Restricting NetworkPolicy changes for security reasons
  # roles:
  #   - name: dev
  #     description: dev role with full permissions
  #     policies:
  #       - p, role:dev, applications, *, microservice-project/*, allow
  #       - p, role:dev, projects, get, microservice-project, allow
  #     groups:
  #       - dev-team
  #   - name: read-only
  #     description: read-only role with view permissions
  #     policies:
  #       - p, role:read-only, applications, get, microservice-project/*, allow
  #       - p, role:read-only, applications, sync, microservice-project/*, allow